package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'B'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("B")) {
    expectSteps {
        step {
            name = "Resharper - Duplicates"
            type = "dotnet-tools-dupfinder"
            param("dotnet-tools-dupfinder.discard_cost", "60")
            param("dotnet-tools-dupfinder.exclude_files", """
                **/*.Designer.cs
                Database/**
                **UnitTests**
                **/AssemblyInfo.cs
                EnergyWorkbench/Examples/**
                EnergyWorkbench/Tests/**
                **/ScipApi.*.cs
                ExcelTools/Sandbox/**
                **/LpSolveApi.cs
                **/*.generated.cs
            """.trimIndent())
            param("dotnet-tools-dupfinder.hashing.discard_fields_name", "false")
            param("dotnet-tools-dupfinder.hashing.discard_local_variables_name", "false")
            param("dotnet-tools-dupfinder.hashing.discard_types", "false")
            param("dotnet-tools-dupfinder.hashing.normalize_types", "true")
            param("jetbrains.resharper-clt.clt-path", "%teamcity.tool.jetbrains.resharper-clt.DEFAULT%")
        }
        script {
            executionMode = BuildStep.ExecutionMode.RUN_ON_FAILURE
            scriptContent = "ping -n 120 localhost > NUL"
        }
    }
    steps {
        update<ScriptBuildStep>(1) {
            clearConditions()
            scriptContent = "ping -n 30 localhost > NUL"
        }
    }
}
