package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildStep
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'ResharperDuplicates'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("ResharperDuplicates")) {
    expectSteps {
        step {
            name = "Resharper - Duplicates"
            type = "dotnet-tools-dupfinder"
            param("dotnet-tools-dupfinder.exclude_files", """
                **/*.Designer.cs
                Database/**
                **UnitTests**
                **/AssemblyInfo.cs
                EnergyWorkbench/Examples/**
                EnergyWorkbench/Tests/**
                **/ScipApi.*.cs
                ExcelTools/Sandbox/**
                **/LpSolveApi.cs
                **/*.generated.cs
            """.trimIndent())
            param("dotnet-tools-dupfinder.hashing.discard_fields_name", "false")
            param("dotnet-tools-dupfinder.hashing.discard_local_variables_name", "false")
            param("dotnet-tools-dupfinder.hashing.discard_types", "true")
            param("dotnet-tools-dupfinder.hashing.normalize_types", "true")
        }
        script {
            scriptContent = "ping 127.0.0.1 -n 60 > nul"
        }
    }
    steps {
        update<BuildStep>(0) {
            clearConditions()
            param("dotnet-tools-dupfinder.discard_cost", "50")
            param("jetbrains.resharper-clt.clt-path", "%teamcity.tool.jetbrains.resharper-clt.DEFAULT%")
            param("dotnet-tools-dupfinder.hashing.discard_local_variables_name", "")
            param("dotnet-tools-dupfinder.hashing.discard_fields_name", "")
            param("dotnet-tools-dupfinder.hashing.discard_types", "")
            param("dotnet-tools-dupfinder.hashing.normalize_types", "")
            param("dotnet-tools-dupfinder.hashing.discard_literals", "")
        }
    }
}
